#  _____     ______     __     __   __
# /\  __-.  /\  ___\   /\ \   /\ "-.\ \
# \ \ \/\ \ \ \  __\   \ \ \  \ \ \-.  \
#  \ \____-  \ \_____\  \ \_\  \ \_\\"\_\
#   \/____/   \/_____/   \/_/   \/_/ \/_/
#
#  __         ______     ______     __  __
# /\ \       /\  __ \   /\___  \   /\ \_\ \
# \ \ \____  \ \  __ \  \/_/  /__  \ \____ \
#  \ \_____\  \ \_\ \_\   /\_____\  \/\_____\
#   \/_____/   \/_/\/_/   \/_____/   \/_____/

# -----python設定----- {{{

[[plugins]] # vimのマニュアル参照
repo = 'davidhalter/jedi-vim' # {{{
on_ft = 'python'
# jediにおける変数リネーム機能とquickrun実行コマンドのcompeteをクリアしておく
hook_add = '''
    let g:jedi#rename_command = "<Leader>R"
    let g:jedi#force_py_version = 3
'''
# }}}

[[plugins]] # text objectをpythonのdefとClassで設定できます
repo = 'bps/vim-textobj-python' # {{{
on_ft = 'python'
# }}}

[[plugins]] # python editing mode
repo = 'python-mode/python-mode' # {{{
on_ft = 'python'
hook_add = '''
    let g:pymode_python = 'python3'
    let g:pymode_run = 0
    let g:pymode_run_bind = '<leader>_'
'''
# }}}

# Not In Use {{{

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv' # {{{
# depends = 'davidhalter/jedi-vim'
# on_ft = 'python'
# # }}}

# [[plugins]]
# repo = 'hynek/vim-python-pep8-indent' # {{{
# on_ft = 'python'
# # }}}

# [[plugins]]
# repo = 'andviro/flake8-vim' # {{{
# on_ft = 'python'
# # }}}

# }}}

# }}}

# ----- markdown関連 ----- {{{

[[plugins]] # 自動タグ補完
repo = 'alvan/vim-closetag' # {{{
on_ft = ['markdown', 'html']
hook_add = '''
    let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.md,*.markdown,*.mkdown,*.mdown'
    let g:closetag_xhtml_filenames = '*.xhtml,*.jsx'
    let g:closetag_filetypes = 'html,xhtml,phtml,markdown'
    let g:closetag_xhtml_filetypes = 'xhtml,jsx'
'''
# }}}

[[plugins]] # stand aloneに使えるMarkdown Previewer, Mermeid記法も使える
repo = 'kannokanno/previm' # {{{
on_ft = ['markdown','txt']
hook_add = '''
    let g:previm_open_cmd = 'open -a Safari'
    let g:previm_enable_realtime = 1
    let g:previm_disable_default_css = 1
    let g:previm_custom_css_path = '~/.pandoc/github.css'
    nnoremap <silent> <Leader>P :PrevimOpen<CR>
    " autocmd BufNewFile,BufRead *.{md,mkd,mkdn,mdwn,mdown,markdown} PrevimOpen
'''
# }}}

[[plugins]] # markdownでoutlineを作る専用
repo = 'Shougo/unite.vim' # {{{
on_ft = ['markdown']
# }}}

[[plugins]] # アウトラインの自動作成
repo = 'Shougo/unite-outline' # {{{
hook_add = '''
    nnoremap <Leader>ol :<C-u>Denite -mode=normal -cursor-wrap=true -split=vertical unite:outline<CR>
'''
depends = 'unite.vim'
on_ft = ['markdown']
# }}}

[[plugins]] # citation
repo = 'rafaqz/citation.vim' # {{{
hook_add = '''
    let g:citation_vim_bibtex_file="~/.pandoc/library.bib"
    let g:citation_vim_mode="bibtex"
    let g:citation_vim_cache_path='~/.vim/citation_cache'
    let g:citation_vim_outer_prefix="["
    let g:citation_vim_inner_prefix="@"
    let g:citation_vim_suffix="]"
    let g:citation_vim_et_al_limit=2
    nnoremap <silent> <leader>c :<C-u>Denite -direction=topleft -mode=normal -cursor-wrap=true -split=vertical unite:citation/key<CR>
    nnoremap <silent> [denite]k :<C-u>Denite -direction=topleft -mode=normal -cursor-wrap=true -split=vertical unite:citation/key<CR>
    nnoremap <silent> [denite]a :<C-u>Denite -direction=topleft -mode=normal -cursor-wrap=true -split=vertical unite:citation/abstract<CR>
    nnoremap [denite]i :<C-u>Denite -direction=topleft -mode=normal -cursor-wrap=true -split=vertical unite:citation<CR>
'''
depends = 'unite.vim'
on_ft = ['markdown']
# }}}

# Not In Use {{{

# [[plugins]] # Markdownプレビューワ, 先にnpm -g install instant-markdown-dが必要
# repo = 'suan/vim-instant-markdown' # {{{
# on_ft = 'markdown'
# # }}}

# [[plugins]] # Markdown
# repo = 'rcmdnk/vim-markdown' # {{{
# on_ft = ['markdown','mkd']
# hook_add = '''
#     let g:vim_markdown_frontmatter = 1
#     let g:vim_markdown_math = 1
# '''
# # }}}

# [[plugins]] # HTMLタグの自動補完
# repo = 'vim-scripts/HTML-AutoCloseTag' # {{{
# on_ft = ['markdown', 'html']
# # }}}

# }}}

# }}}

# ----- その他 ----- {{{

[[plugins]] # toml syntax
repo = 'cespare/vim-toml' # {{{
on_ft = 'toml'
# }}}

[[plugins]] # diffsplitが便利になるよ
repo = 'chrisbra/vim-diff-enhanced' # {{{
# }}}

[[plugins]] # cow, comment out plugin
repo = 'tyru/caw.vim' # {{{
on_ft = ['python', 'html', 'markdown', 'vim', 'toml', 'zsh']
hook_add = '''
    nmap gcc <Plug>(caw:wrap:toggle)
    vmap gcc <Plug>(caw:wrap:toggle)
'''
# }}}

[[plugins]] # For Excel viewer and vimplenote-vim
repo = 'mattn/webapi-vim' # {{{
# }}}

[[plugins]] # Excel viewer (only .xlsx)
repo = 'mattn/excelview-vim' # {{{
depends = 'webapi-vim'
# }}}

[[plugins]] # カーソル下の語が自動ハイライトされる
repo = 'itchyny/vim-cursorword' # {{{
on_ft = ['python', 'html', 'toml', 'c']
# }}}

[[plugins]] # カラムをモーション範囲に
repo = 'idbrii/textobj-word-column.vim' # {{{
depends = 'vim-textobj-user'
# }}}

# Not In Use {{{
# }}}

# }}}

# vim: set foldmethod=marker :
