# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \   'colorscheme': 'wombat'
    \}
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]] 
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]] # 括弧の操作を楽にする
repo = 'tpope/vim-surround'

[[plugins]] # 行末の不要な半角スペースを可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # インデントによる階層を分かりやすく可視化
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # CSVなどの成型に
repo = 'junegunn/vim-easy-align'
# ビジュアルモードで選択し，easy-align 呼んで整形．(e.g. vip<Enter>)
# easy-align を呼んだ上で，移動したりテキストオブジェクトを指定して整形．(e.g. gaip)
hook_add = '''
    vmap <Enter> <Plug>(EasyAlign)
    nmap ga <Plug>(EasyAlign)
'''

[[plugins]] # diffsplitが便利になるよ
repo = 'chrisbra/vim-diff-enhanced'

[[plugins]] # :CalendarでGoogleカレンダーを開けます
repo = 'itchyny/calendar.vim'
hook_add = '''
    let g:calendar_google_calendar = 1
    let g:calendar_first_day = 'monday'
'''

[[plugins]] # 日本語IMEに影響しない括弧補完
repo = 'itmammoth/doorboy.vim'
hook_add = '''
    let g:doorboy_additional_quotations = {
    \ 'markdown': ['*'],
    \ }
'''
# hook_add = '''
# let g:doorboy_additional_brackets = {
#     \ '*': ['「」'],
#     \ }
# '''

# [[plugins]] # vim内移動用
repo = 'easymotion/vim-easymotion'
# EasyMotionのleader keyを<Space>fにする
# fコマンドを，easymotionのfモードにする
hook_add = '''
    let g:EasyMotion_leader_key = '<Space>f'
    let g:EasyMotion_use_migemo = 1
    nmap <Space>ff <Plug>(easymotion-overwin-f)
    nmap <Space>fs <Plug>(easymotion-overwin-f2)
    nmap <Space>ft <Plug>(easymotion-t2)
    nmap <Space>f/ <Plug>(easymotion-sn)
'''

[[plugins]] # コードブロックでvim内移動
repo = 'haya14busa/vim-edgemotion'
hook_add = '''
    map <C-j> <Plug>(edgemotion-j)
    map <C-k> <Plug>(edgemotion-k)
'''

[[plugins]] # <C-a>,<C-x>でleft<->rightなど対義語変換, zef/vim-cycleよりfork
repo = 'ishibaki/vim-cycle'

[[plugins]] # vim上でプログラムの非同期実行
repo = 'thinca/vim-quickrun'
# <Leader>rで実行されるのでよろしく

[[plugins]] # アウトラインの自動作成
repo = 'Shougo/unite-outline'
hook_add = '''
    nmap <Leader>ol :Unite outline<CR>
'''

[[plugins]] # vim-table-mode
repo = 'dhruvasagar/vim-table-mode'
# markdownのときにはマークダウン文法の表形式に変更
hook_add = '''
    augroup vimTableMode
        autocmd!
        autocmd BufNewFile,BufRead *.md let g:table_mode_corner='|'
        autocmd BufNewFile,BufRead *.mdown let g:table_mode_corner='|'
    augroup END
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'

# [[plugins]] # 英語単語の自動補完
# repo = 'ujihisa/neco-look'
# on_i = 1
# depends = 'neocomplete.vim'

# [[plugins]] # メモ用プラグイン
# repo = 'glidenote/memolist.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# hook_post_update = '''
#   if dein#util#_is_windows()
#     let cmd = 'tools\\update-dll-mingw'
#   elseif dein#util#_is_cygwin()
#     let cmd = 'make -f make_cygwin.mak'
#   elseif executable('gmake')
#     let cmd = 'gmake'
#   else
#     let cmd = 'make'
#   endif
#   let g:dein#plugin.build = cmd
# '''

# ブランチやタグを指定したいとき
# [[plugins]]
# repo = 'delphinus35/typescript-vim'
# rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
# [[plugins]]
# repo = 'elzr/vim-json'
# if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
# [[plugins]]
# repo    = 'vim-airline/vim-airline'
# depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
