#  _____     ______     __     __   __
# /\  __-.  /\  ___\   /\ \   /\ "-.\ \
# \ \ \/\ \ \ \  __\   \ \ \  \ \ \-.  \
#  \ \____-  \ \_____\  \ \_\  \ \_\\"\_\
#   \/____/   \/_____/   \/_/   \/_/ \/_/
#
#  __         ______     ______     __  __
# /\ \       /\  __ \   /\___  \   /\ \_\ \
# \ \ \____  \ \  __ \  \/_/  /__  \ \____ \
#  \ \_____\  \ \_\ \_\   /\_____\  \/\_____\
#   \/_____/   \/_/\/_/   \/_____/   \/_____/

# -----python設定-----

[[plugins]] # vimのマニュアル参照
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
# jediにおける変数リネーム機能とquickrun実行コマンドのcompeteをクリアしておく
hook_add = '''
    let g:jedi#rename_command = "<Leader>R"
'''

[[plugins]] # text objectをpythonのdefとClassで設定できます
repo = 'bps/vim-textobj-python'
on_ft = 'python'

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# depends = 'davidhalter/jedi-vim'
# on_ft = 'python'

# [[plugins]]
# repo = 'hynek/vim-python-pep8-indent'
# on_ft = 'python'

# [[plugins]]
# repo = 'andviro/flake8-vim'
# on_ft = 'python'

# ----- markdown関連 -----

[[plugins]] # HTMLタグの自動補完
repo = 'vim-scripts/HTML-AutoCloseTag'
on_ft = ['markdown', 'html']

[[plugins]] # stand aloneに使えるMarkdown Previewer, Mermeid記法も使える
repo = 'kannokanno/previm'
on_ft = ['markdown','txt']
hook_add = '''
    let g:previm_open_cmd = 'open -a Safari'
    let g:previm_enable_realtime = 1
    let g:previm_disable_default_css = 1
    let g:previm_custom_css_path = '~/.pandoc/github.css'
    nnoremap <silent> <Leader>P :PrevimOpen<CR>
    autocmd BufNewFile,BufRead *.{md,mkd,mkdn,mdwn,mdown,markdown} PrevimOpen
'''

# [[plugins]] # Markdownプレビューワ, 先にnpm -g install instant-markdown-dが必要
# repo = 'suan/vim-instant-markdown'
# on_ft = 'markdown'

# [[plugins]] # Markdown
# repo = 'rcmdnk/vim-markdown'
# on_ft = ['markdown','mkd']
# hook_add = '''
#     let g:vim_markdown_frontmatter = 1
#     let g:vim_markdown_math = 1
# '''

# ----- その他 -----

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # diffsplitが便利になるよ
repo = 'chrisbra/vim-diff-enhanced'

