# -----python設定-----

# [[plugins]]
# repo = 'hynek/vim-python-pep8-indent'
# on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]] # Markdownプレビューワ, 先にnpm -g install instant-markdown-dが必要
repo = 'suan/vim-instant-markdown'
on_ft = ['markdown','mkd','mdown']

[[plugins]] # HTMLタグの自動補完
repo = 'vim-scripts/HTML-AutoCloseTag'
on_ft = ['markdown','mkd','mdown', 'html']

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# depends = 'davidhalter/jedi-vim'
# on_ft = 'python'

# [[plugins]]
# repo = 'jmcantrell/vim-virtualenv'
# on_ft = 'python'

# [[plugins]]
# repo = 'andviro/flake8-vim'
# on_ft = 'python'


# -----Markdown設定-----
# [[plugins]] # Markdown
# repo = 'rcmdnk/vim-markdown'
# on_ft = ['markdown','mkd']
# hook_add = '''
#     let g:vim_markdown_frontmatter = 1
#     let g:vim_markdown_math = 1
# '''

# -----一般設定-----

[[plugins]]
repo = 'Shougo/neocomplete.vim'
insert = 1

